package com.aiadvent.backend.chat.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;

@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Token usage statistics returned by the provider.")
public record StructuredSyncUsageStats(
    @Schema(description = "Tokens consumed by the prompt.", example = "350") Integer promptTokens,
    @Schema(description = "Tokens generated by the model.", example = "512") Integer completionTokens,
    @Schema(description = "Total tokens for the interaction.", example = "862") Integer totalTokens) {}
